version: "3.8"

services:
  snapstyle-backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    networks:
      - snapstyle-network
    volumes:
      - .:/app

  snapstyle-frontend:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://snapstyle-backend:8000
    depends_on:
      - snapstyle-backend
    networks:
      - snapstyle-network

networks:
  snapstyle-network:
    driver: bridge
