version: "3.8"

services:
  snapstyle-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    networks:
      - snapstyle-network
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app

  snapstyle-frontend:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://snapstyle-backend:8000
    depends_on:
      - snapstyle-backend
    networks:
      - snapstyle-network
    volumes:
      - ./streamlit_app:/app/streamlit_app

networks:
  snapstyle-network:
    driver: bridge
